### ISSUE TITLE
treemap example fails on d3.show()

### ISSUE THREAD

**Issue by matthewcriswell** [d3blocks/d3blocks#32]
When attempting to run the final step of the treemap example I get a failure:

```
>>> from d3blocks import D3Blocks
>>> d3 = D3Blocks(chart='Treemap', frame=True)
<brevity>
>>> df = d3.import_example('energy')
<brevity>
>>> d3.set_node_properties(df)
<brevity>
>>> print(d3.node_properties)
<brevity>
>>> d3.set_edge_properties(df)
<brevity>
>>> print(d3.edge_properties)
<brevity>
>>> d3.show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattcriswell/github/tech_debt_analysis/.venv/lib/python3.11/site-packages/d3blocks/d3blocks.py", line 2190, in show
    html = self.chart.show(self.edge_properties, config=self.config, node_properties=self.node_properties, logger=logger, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattcriswell/github/tech_debt_analysis/.venv/lib/python3.11/site-packages/d3blocks/treemap/Treemap.py", line 133, in show
    return write_html(X, config, logger)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattcriswell/github/tech_debt_analysis/.venv/lib/python3.11/site-packages/d3blocks/treemap/Treemap.py", line 177, in write_html
    index_template = jinja_env.get_template('treemap.html.j2')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattcriswell/github/tech_debt_analysis/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattcriswell/github/tech_debt_analysis/.venv/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattcriswell/github/tech_debt_analysis/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattcriswell/github/tech_debt_analysis/.venv/lib/python3.11/site-packages/jinja2/loaders.py", line 344, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: treemap.html.j2
```

I noticed I seemed to be missing the treemap.html.j2 file:
```
site-packages $ tree d3blocks/treemap/
d3blocks/treemap/
├── Treemap.py
├── __init__.py
├── __pycache__
│   ├── Treemap.cpython-311.pyc
│   └── __init__.cpython-311.pyc
└── d3js
    ├── __init__.py
    └── __pycache__
        └── __init__.cpython-311.pyc
```

After manually copying the file(s) from the repo everything seemed to work:
```
site-packages $ tree d3blocks/treemap/
d3blocks/treemap/
├── Treemap.py
├── __init__.py
├── __pycache__
│   ├── Treemap.cpython-311.pyc
│   └── __init__.cpython-311.pyc
└── d3js
    ├── __init__.py
    ├── __pycache__
    │   └── __init__.cpython-311.pyc
    ├── d3.v4.min.js
    └── treemap.html.j2
```

My suspicion is that the file is being missed when you build locally because of the treemap `__pycache__` directory not being cleared in the [make_clean.sh](https://github.com/d3blocks/d3blocks/blob/f2b73efd705318252a5c6e483802136bf1b06d38/make_clean.sh#L18) script.

Though it's not impossible that there's something wrong with my environment or perhaps there is some user error on my end.

This happens in a fresh virtual environment.  My system is running:
```
Python 3.11.2 (main, Feb 16 2023, 02:55:59) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
```

**Comment by erdogant** [comment]
Should be fix now! update with: `pip install -U d3blocks`

**Comment by matthewcriswell** [comment]
Confirmed fixed.  Awesome project, by the way!

**Comment by melaasar** [comment]
I think the same problem exists for the `tree` widget. It's also missing the tree.html.j2 file in the released package.

**Comment by erdogant** [comment]
The files seems to be there. Did you also try the toy-example as shown on the [documentation pages](https://d3blocks.github.io/d3blocks/pages/html/Tree.html)?

**Comment by melaasar** [comment]
I updated but it is still missing these files.
<img width="293" alt="Screenshot 2023-08-24 at 1 42 22 PM" src="https://github.com/d3blocks/d3blocks/assets/5720252/8116c6d0-5e23-40de-94df-09501bc9e5fd">

**Comment by erdogant** [comment]
This triggered me and yes you are right. The files were not shipped in the package because this new block was not included in the MANIFEST. Try again, with a force update. It should work now.
